from enum import IntEnum
class StatusCode(IntEnum):
    OK = 0
    ERROR_WRONG_UID_FORMAT = 1
    ERROR_LINK_REQUIRED = 2
    ERROR_SIGNATURE_REQUIRED = 3
    ERROR_SIGNATURE_VERIFICATION_FAILED = 4
    ERROR_TABLE_NOT_EXISTS = 5
    ERROR_NO_SUCH_USER_IN_TABLE = 6
    ERROR_DAEMON_IS_NOT_RUNNING = 7
    ERROR_WRONG_LINK = 8
    ERROR_WRONG_ENCODING = 9
